# Generated by Django 5.2.4 on 2026-06-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('forecast_type', models.CharField(choices=[('SALES', 'Sales'), ('DEMAND', 'Demand'), ('PROFIT', 'Profit'), ('CASHFLOW', 'Cash Flow')], max_length=50)),
                ('forecast_date', models.DateField()),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kpi_type', models.CharField(choices=[('SALES', 'Sales'), ('PROFIT', 'Profit'), ('CUSTOMERS', 'Customers'), ('INVENTORY', 'Inventory'), ('EXPENSES', 'Expenses')], max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('PROFIT_LOSS', 'Profit & Loss'), ('BALANCE_SHEET', 'Balance Sheet'), ('CASHFLOW', 'Cash Flow'), ('PAYROLL', 'Payroll')], max_length=50)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('email_to', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('implemented', models.BooleanField(default=False)),
                ('impact_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('SALES_CHART', 'Sales Chart'), ('PROFIT_CHART', 'Profit Chart'), ('INVENTORY', 'Inventory'), ('CUSTOMERS', 'Customers'), ('FORECAST', 'Forecast'), ('KPI', 'KPI')], max_length=50)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
