# Generated by Django 5.2.4 on 2026-06-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountlockout_activitylog_alloweddevice_allowedip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alloweddevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
