# Generated by Django 5.2.4 on 2026-06-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alloweddevice_created_at_alloweddevice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
